# Copyright Microsoft Corporation
# This Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment.
# THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE. 
# We grant You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form of the Sample Code, provided that You agree:
# (i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded;
# (ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; and
# (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits, including attorneys’ fees, that arise or result from the use or distribution of the Sample Code.
# Please note: None of the conditions outlined in the disclaimer above will supersede the terms and conditions contained within the Premier Customer Services Description.


name: Export Org Demo solutions Dev with Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'name of the git branch'
        required: false
        default:  '001'
      branch-type:
        description: 'type of branch'
        required: true
        type: choice
        options:
        - feature
        - hotfix
        - bugfix
        - development
      source-Environment:
        description: 'Source Development Environment'
        type: environment
        required: true
        default: 'Contoso Development'
      delete-existing-source:
        description: 'delete existing source file before export'
        type: boolean
        required: false
        default: true
env:
  solution-names: "'['OrgDemo','OrgLocation']"

jobs:
  setup:
    environment: ${{ inputs.source-Environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        solution-name: ${{ toJson("'['OrgDemo','OrgLocation']") }}
    steps:    
    - name: Variables      
      run: |        
        echo "Solution Name : ${{ matrix.solution-name }}"        
        echo "URI ${{ vars.POWERPLATFORMURI }}"        
        echo "Source ${{ vars.POWERPLATFORMORGURI_DEV }}"   
    # - name: Debug output
    #   shell: pwsh
    #   run: |
    #     Get-ChildItem -Recurse | foreach { write-host $_.FullName }
  #createBranch:
  #  needs: [setup]
  #  uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-createBranch.yml@main
  #  with: 
  #    branch-name: ${{ inputs.branch-name }}
  #    branch-type: ${{ inputs.branch-type }}
  #  secrets: inherit
  # export:
  #   needs: [setup]      
  #   uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-export-solution.yml@main
  #   with: 
  #     environment: ${{ inputs.source-Environment }}
  #     solution-name: ${{ inputs.solution-name }}
  #     ClearEnvironmentVariableValues: true
  #     isCommit: true
  #     branch-name: ${{ inputs.branch-name }}
  #     branch-type: ${{ inputs.branch-type }}
  #     commitMessage: 'Export Solution ${{ inputs.solution-name }}'
  #     folder-path: '.'
  #     VersionReleaseIncrement: 1
  #     delete-existing-source: ${{ inputs.delete-existing-source }}
  #   secrets: inherit
      
