# Copyright Microsoft Corporation
# This Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment.
# THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE. 
# We grant You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form of the Sample Code, provided that You agree:
# (i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded;
# (ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; and
# (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits, including attorneys’ fees, that arise or result from the use or distribution of the Sample Code.
# Please note: None of the conditions outlined in the disclaimer above will supersede the terms and conditions contained within the Premier Customer Services Description.

# This is a basic workflow to help you get started with Actions

name: workflow-import-solution 

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      solution-name:
        description: "Solution Name"
        type: string
        required: true
        default: 'OrgDemo'
      environment:
        type: string
        required: true
      branch-name:
        type: string
        required: false
      branch-type:
        type: string
        required: false
      folder-path:
        type: string
        required: false
        default: 'PowerPlatformALM'
      release-name:
        type: string
        required: false
        default: '.'
      managed:
        type: boolean
        required: false
        default: true
      settings-file:
        type: string
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  import:
    environment: ${{ inputs.environment }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          lfs: true
          sparse-checkout: |
            .
            .github
            src
            release          
      - name: check out branch if exists
        run: |
          git config --global user.email '${{ github.actor }}'
          git config --global user.name "${{ github.actor }}@contoso.willinc.ca"
          git fetch
          git show-ref
          $branchName = "${{ inputs.branch-type }}/${{ inputs.branch-name }}"
          $branchExists = ($null -ne (git ls-remote --heads origin "$branchName"))
          if ($branchExists) {          
            echo "Branch exists. Checking out..."
            git checkout origin/${{ inputs.branch-name }}
            git switch ${{ inputs.branch-name }}
            git pull origin ${{ inputs.branch-name}} 
          } else {
            echo "Branch does not exist."
          }
          git status
          echo "branch-exists=$branchExists" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append;
        shell: pwsh
      - name: Checkout Template Branch 
        uses: actions/checkout@v4
        with:
          repository: Contoso-W-Enterprise/PowerPlatformALM
          ref: main
          path: ALMTemplate
          github-server-url: 'https://github.com'
          lfs: true
          sparse-checkout: |
            .github
            PowerShell
          persist-credentials: true
      - name: Set release variables
        run: |
          $solutionName = '${{ inputs.solution-name }}';
          write-Host "solution name $solutionName"
          write-host "release name ${{inputs.release-name}}"
          write-host "folder path ${{inputs.folder-path}}"
          
          if (("${{inputs.release-name}}").length -gt 1)
          {
            $releaseName = "${{inputs.release-name}}"
            write-host "release name: $releaseName"     
            if (("${{inputs.folder-path}}").length -gt 1 )
            {
              $releasePath = "${{inputs.folder-path}}" + '/release/'+ $releaseName + '/'
            } else {
              $releasePath = 'release/' + $releaseName +'/'
            }
          } else {
            write-host "release name: null"     
            if (("${{inputs.folder-path}}").length -gt 1 )
            {
              if (Test-Path -LiteralPath "${{inputs.folder-path}}/release") {
                write-host "tested ${{inputs.folder-path}}/release successful"
                $latestRelease = (Get-ChildItem -path "${{inputs.folder-path}}/release"  -File "$solutionName.zip -Recurse | Sort-Object -Property LastWriteTime -Descending -top 1).DirectoryName            
                write-host "latest release: $($latestRelease)"
                $releasePath = "${{inputs.folder-path}}/release/" + $latestRelease + '/' 
              } else {
                write-host "Release folder not found"
              }
            } else {
              if (Test-Path -LiteralPath "release") {
                write-host "tested release successful"
                $latestRelease = (Get-ChildItem -path "release"  -File "$solutionName.zip -Recurse | Sort-Object -Property LastWriteTime -Descending -top 1).DirectoryName            
                write-host "latest release: $($latestRelease)"
                $releasePath = 'release/'+ $latestRelease + '/'
              } else {
                write-host "Release folder not found"
              }
            }
          }
          write-Host "release path $releasePath";
          echo "release-name=$releaseName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append;
          echo "release-path=$releasePath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append;
        shell: pwsh
      - name: Debug list of files
        run: |
          Get-ChildItem -path '.' -Recurse | foreach { write-host $_.FullName }
        shell: pwsh
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
      - name: Check solution exists
        id: check-solution-exists
        run: |
          . "${{ github.workspace }}/ALMTemplate/PowerShell/PowerPlatform-Utility.ps1"
          import-DataverseWebAPI "${{ github.workspace }}/ALMTemplate"
          $solutionName = '${{ Inputs.solution-name }}';
          $token = Connect-Dataverse -dataverseHost '${{ vars.POWERPLATFORMORGURI }}' -tenantId ${{ secrets.POWERPLATFORMCONTOSOTENANTID }} -clientId ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }} -clientSecret ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }} 
          $results = Get-DataverseSolution -token $token -dataverseHost '${{ vars.POWERPLATFORMORGURI }}' -solutionUniqueName $solutionName
          if($solutionName -in $results.uniquename)
          {
              echo "check-solution-exists=true" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append; 
          }
          else 
          {
              echo "check-solution-exists=false" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append; 
          }
        shell: pwsh
      - name: Test pwsh output
        run: |
          echo ${{ env.check-solution-exists }}
      #managed solution
      - name: check managed solution
        if: ${{ inputs.managed == 'true'}}
        uses: microsoft/powerplatform-actions/check-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          path: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}_managed.zip'
      #managed solution & setting file & solution exists
      - name: import upgrade managed Solution with settings file
        if: ${{ inputs.managed  == true && inputs.setting-file != '' && env.check-solution-exists  == true }}
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          solution-file: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}_managed.zip'
          stage-and-upgrade: true
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: true
          deployment-settings-file: ${{ inputs.settings-file }}
          run-asynchronously: true
      #managed solution & setting file & solution not exists
      - name: import new managed Solution with settings file
        if: ${{ inputs.managed  == true && inputs.setting-file != '' && env.check-solution-exists  != true }}
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          solution-file: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}_managed.zip'
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: true
          deployment-settings-file: ${{ inputs.settings-file }}
          run-asynchronously: true
      #managed solution & no setting file & solution exists
      - name: import upgrade managed Solution with out settings file
        if: ${{ inputs.managed == true && inputs.setting-file == '' &&  env.check-solution-exists  == true }}
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          solution-file: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}_managed.zip'
          stage-and-upgrade: true
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: false
          run-asynchronously: true
      #managed solution & no setting file & solution not exists
      - name: import new managed Solution with out settings file
        if: ${{ inputs.managed == true && inputs.setting-file == '' && env.check-solution-exists != true }}
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          solution-file: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}_managed.zip'
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: false
          run-asynchronously: true

      # unmanaged solution
      - name: check unmanaged solution
        if: ${{ inputs.managed == false }}
        uses: microsoft/powerplatform-actions/check-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          path: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}.zip'
      # unmanaged solution & solution file & solution exist
      - name: Import upgrade Unmanaged Solution with settings file
        if: ${{ inputs.managed == false && inputs.setting-file != '' && env.check-solution-exists == true }}
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          solution-file: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}.zip'
          stage-and-upgrade: true
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: true
          deployment-settings-file: ${{ inputs.settings-file }}
          run-asynchronously: true
      # unmanaged solution & solution file & solution not exist
      - name: Import new Unmanaged Solution with settings file
        if: ${{ inputs.managed  == false && inputs.setting-file != '' && env.check-solution-exists != true }}
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          solution-file: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}.zip'
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: true
          deployment-settings-file: ${{ inputs.settings-file }}
          run-asynchronously: true
      # unmanaged solution & not solution file & solution exist
      - name: Import upgrade Unmanaged Solution without settings file
        if: ${{ inputs.managed == false && inputs.setting-file == '' && env.check-solution-exists == true }}
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          solution-file: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}.zip'
          stage-and-upgrade: true
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: false
          run-asynchronously: true
      # unmanaged solution & not solution file & solution not exist
      - name: Import new Unmanaged Solution without settings file
        if: ${{ inputs.managed == false && inputs.setting-file == '' && env.check-solution-exists != true }}
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMCONTOSOCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMCONTOSOCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOTENANTID }}
          solution-file: '${{ inputs.folder-path }}/${{ env.release-path }}${{ inputs.solution-name }}.zip'
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: false
          run-asynchronously: true
